services:
  bitwarden:
    image: ghcr.io/bitwarden/lite:2025.12.2
    container_name: bitwarden
    restart: always
    volumes:
      - ./data:/etc/bitwarden
    environment:
      BW_DOMAIN: bw.${DOMAIN}
      BW_INSTALLATION_ID: ${BW_INSTALLATION_ID}
      BW_INSTALLATION_KEY: ${BW_INSTALLATION_KEY}
      BW_DB_PROVIDER: sqlite
      BW_DB_FILE: /etc/bitwarden/vault.db
      BW_ENABLE_SSL: "false"
      BW_ENABLE_ADMIN: "false"
      globalSettings__baseServiceUri__vault: "https://bw.${DOMAIN}"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`bw.${DOMAIN}`)"
      - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`bw.${DOMAIN}`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
